# Generated by Django 2.0.7 on 2018-07-28 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
        ('enderecos', '0001_initial'),
        ('comentarios', '0002_auto_20180727_1701'),
        ('atracoes', '0001_initial'),
        ('core', '0005_pontosturisticos_endereco'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PontosTuristicos',
            new_name='PontoTuristico',
        ),
    ]
